FROM ubuntu:latest

LABEL version="0.0.1"

LABEL maintainer="piyush.baronia.devops@gmail.com"

RUN apt-get update

RUN apt-get upgrade -y

RUN apt-get install nginx -y

EXPOSE 10

CMD ["nginx","-g","daemon off" ]


